name: manage-azure-policy-a0a4d0de
on:
  push:
    paths:
      - policies/policies/[ThisIsForTest]-A-test-definition_75b3b84e-3326-49de-a16e-5931ae58f3ba/**
      - .github/workflows/manage-azure-policy-a0a4d0de.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_a0a4d0de}}
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          policies/policies/\\[ThisIsForTest\\]-A-test-definition_75b3b84e-3326-49de-a16e-5931ae58f3ba/**

